# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome do candidato')),
                ('numero', models.SmallIntegerField(verbose_name='N\xfamero do candidato')),
                ('partido', models.CharField(max_length=10, verbose_name='Nome do partido')),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500, verbose_name='Texto da proposta')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presidenciaveis.Candidato')),
            ],
        ),
    ]
