# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presidenciaveis', '0002_auto_20180914_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='\xc1rea'),
        ),
    ]
